version: "3.9"

services:
  parser:
    image: parser_image
    container_name: parser_container
    build: .
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - /home/aayush/Docker_data/database.db:/app/database.db
      - /home/aayush/Docker_data/logs:/app/logs
      - /home/aayush/Docker_data/json_logs:/app/json_logs/
      - /home/aayush/Docker_data/prometheus_data:/app/prometheus_data
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///app/database.db
      - PROMETHEUS_MULTIPROC_DIR=/app/prometheus_data
    command: >
      /bin/sh -c "rm -rf /app/prometheus_data/* &&
      PROMETHEUS_MULTIPROC_DIR=/app/prometheus_data gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app"

  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - /home/aayush/Docker_data/prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - parser
